### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by eliaskg**
Hey Randy,

couldn't resist. I added some stuff:
- Sidebar icons are now selectable with proper animations.
- Implemented search view

Problems:
- The normal CPSearchField is too tall for the breadcrumb view. (You can see it when you select it) Maybe we need a custom design here.
- After performing a search, the row heights are still from the timeline, not from the new content.

Have fun!

Elias

### CODE REVIEW

**Comment by devongovett** [comment]
Thanks Elias!  One thing: the Twitter search thing doesn't load any data in the browser.  It works in NativeHost but in the browser I get `SyntaxError: Unable to parse JSON string`.  Probably a cross-origin thing.

Also, we are probably going to want to make a class for each of those views (mentions, search, etc) rather than putting so much stuff in the AppController.  There should be a separate class for SearchView and MessagesView extending from the base TweetView class so that the custom UI that those views have can be implemented.  Mentions and Tweets would just use TweetView directly.  Just a thought!  I'd like to keep things as modular as possible if we can...

**Comment by devongovett** [comment]
Also, for performance reasons Randy and I had discussed just using two tableviews and switching between them when a button in the sidebar is clicked.  This would fix the other thing that I noticed that is inconsistent from Tweetie, which is that when I go to the search view, perform a search, go to another one of the views and come back to search, the whole thing should be reset (no more tweets, breadcrumbs, etc.).

Thanks for the work!
Devon

**Comment by eliaskg** [comment]
@Devon:
I completely agree that it's no elegant solution to put everything in the AppController. What I tried was simply to get it in the right direction by displaying different tableViews. Now it's possible to look in detail what classes could be put together by subclassing them.
Also the idea with two table views seems good for me in a performance point of view.

@Randy:
I just switched to JSONP on my fork.

**Comment by Me1000** [comment]
I've merged it! Thanks, and keep them coming :D

Something in particular I think would be nice is when you scroll to the bottom have it automatically load the next tweets. 

I'm not really sure how to do this elegantly, the code was a complete mess from the start XD, it was never suppose to develop into a full app. heh

Thanks again!

**Comment by Me1000** [comment]
Oh, I have some more issues :) 

So I think it makes sense to make the serachTable ivar more generic tweetTable2 for example… Then when we switch to unbind the first tableview (to prevent data reloading) and bind it to that one… also reusing the same controller…

You'll notice now that the row heights on the search tweets are wrong because it's pulling the wrong data to calculate the heights.

**Pull request merged**
